id: IB67A7338
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W30182
  ocr_info:
    timestamp: 03/21/23T14:00:56
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 21:10:43.303365+00:00
last_modified: 2024-02-28 21:10:43.303375+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W30182
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30182
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་བློ་བཟང་།
  languages:
  - bo
  author: ཀློང་རྡོལ་བླ་མ་ངག་དབང་བློ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.9781032359817933
  ocr_word_median_confidence_index: 1.0
bases:
  I5937:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5937
      total_pages: 1524
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5937.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9781032359817933
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
